### ISSUE TITLE
assets: split SearchApp into smaller overridable components

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-search-ui#88]
Currently, the `SearchApp` component is defined with a very specific layout that looks something like this:

```
[             searchbar               ] [sort options]

[   facets   ] [              results                ]

[            ] [             pagination              ]
```

In order to add/remove/customize any of the above sections, one needs to completely redefine the entire `SearchApp`. To avoid this, each of these sections, as well as the entire layout, can be wrapped into separate React-Overridable components.

Example use cases:

- I want to add a custom "latest/all versions" toggle button above the facets
- I don't want to have any facets displayed, or I want them to be on the right/top side (instead of the left) 
- I want a table-like layout for my search results (this might also be a nice addition to `react-searchkit`)
- I want to add a "select all" bar which enables selecting search results items to perform bulk actions

**Comment by ntarocco** [comment]
Just a comment on this: IMHO, we should not "abuse" of `Overridable`, because there is no limit to all the possible customizations or layouts.
It is probably a good idea, as you have done, to define the use cases to cover, but then stop there... If you, as user, you need more, you re-define the `SearchApp`.
Take into consideration that, ideally, all this "overridable" areas that allows you to change layout should be somehow documented.

**Comment by slint** [comment]
I agree, the idea is to just cover what 90% of common use-cases need, which is usually small modifications in layout and components, which doesn't require completely rebuilding a `SearchApp`.
